# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c3c287fe9e6de515cbc440d38c24c0ec758204eee8676200794afd7cb91b696168716c9cee58a22fe3a1de116059ec7280930820be8aefb1d903be27e1a36b7

test:
  secret_key_base: 7468e0956eae86a17aa226344845dc67b0c97f42be94919152449299e762e53d5f9f8cf7f96b3e1fa6b9fc285dbc863b5cc88e3b08db22c9ef7041ad46d00060

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
